version: "3.8"
services:
  postgres:
    container_name: pg1
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres

#  pgadmin:
#    links:
#      - postgres:postgres
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    ports:
#      - "8080:80"
#    volumes:
#      - ./data/pgadmin:/root/.pgadmin
#    env_file:
#      - docker.env
#    networks:
#      - postgres

#  keycloak:
#    container_name: keycloak
#    image: quay.io/keycloak/keycloak:17.0.0
#    ports:
#      - "8081:8080"
#    command:
#      - start-dev
#    env_file:
#      - docker.env

  minio:
    container_name: minio01
    image: minio/minio
    volumes:
      - ./data/minio:/data
    ports:
      - "9000:9000"  # Port for API
      - "9001:9001"  # Port for WebUI
    env_file:
      - docker.env
    command: server /data --console-address ":9001"

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=false # Temporary disable xpack.security for dev purposes
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/es01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic
#  es02:
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
#    container_name: es02
#    environment:
#      - node.name=es02
#      - cluster.name=es-docker-cluster
#      - discovery.seed_hosts=es01,es03
#      - cluster.initial_master_nodes=es01,es02,es03
##      - bootstrap.memory_lock=true
#      - xpack.security.enabled=false
#      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
#
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - ./data/es02:/usr/share/elasticsearch/data
#    networks:
#      - elastic
#  es03:
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
#    container_name: es03
#    environment:
#      - node.name=es03
#      - cluster.name=es-docker-cluster
#      - discovery.seed_hosts=es01,es02
#      - cluster.initial_master_nodes=es01,es02,es03
##      - bootstrap.memory_lock=true
#      - xpack.security.enabled=false
#      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - ./data/es03:/usr/share/elasticsearch/data
#    networks:
#      - elastic

  kib01:
    image: docker.elastic.co/kibana/kibana:8.12.2
    container_name: kib01
    depends_on:
      - es01
    environment:
      - ELASTICSEARCH_URL=http://es01:9200
      - ELASTICSEARCH_HOSTS=http://es01:9200
    ports:
      - "5601:5601"
    networks:
      - elastic

networks:
  postgres:
    driver: bridge
  elastic:
    driver: bridge
