version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:17.0.0
    ports:
      - "8081:8080"
    command:
      - start-dev
    env_file:
      - docker.env

  s3server:
    container_name: s3server
    image: scality/s3server
    ports:
      - "8000:8000"

networks:
  postgres:
    driver: bridge
